server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    url: jdbc:mysql://localhost:3306/mts yl?useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  redis:
    host: 192.168.101.65
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    password: redis

logging:
  level:
    com.hmdp: debug