server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    url: jdbc:mysql://localhost:3306/mts yl?useSSL=true
    username: root
    password: 1362775750.+Czh
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.200.131
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON?????????
mybatis-plus:
   type-aliases-package: com.example.mtsyl.entity # ?????
logging:
  level:
    com.hmdp: debug