server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    url: jdbc:mysql://localhost:3306/mts yl?useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

logging:
  level:
    com.hmdp: debug